"""db name to title

Revision ID: 6f2ae347e661
Revises: 89d3ddf3507e
Create Date: 2024-01-22 20:04:49.394657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2ae347e661'
down_revision: Union[str, None] = '89d3ddf3507e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('menu', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('menu', 'title')
    # ### end Alembic commands ###
