"""db second upgrade

Revision ID: 8bb18f85737b
Revises: 58fe9e23b428
Create Date: 2024-01-21 19:45:07.446782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bb18f85737b'
down_revision: Union[str, None] = '58fe9e23b428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dish')
    op.drop_table('under_menu')
    op.drop_table('menu')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('menu_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('count_menus', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='menu_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('under_menu',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('under_menu_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('menu_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], name='under_menu_menu_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='under_menu_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('dish',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('under_menu_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['under_menu_id'], ['under_menu.id'], name='dish_under_menu_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dish_pkey')
    )
    # ### end Alembic commands ###
