# Generated by Django 4.2.6 on 2023-10-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='No Author', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=0, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='subtitle',
            field=models.CharField(default='No Subtitle', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='No Title', max_length=250),
            preserve_default=False,
        ),
    ]
